universe = vanilla
Executable = MT0pW0pB1pJ4pJet1Pt.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = analyze.py,doHists.py,utils.py,weights.py,samples.py
request_memory = 3072
Output = condor_Jet1Pt.out
Error = condor_Jet1Pt.err
Log = condor_Jet1Pt.log
Arguments = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_6_19/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates Jet1Pt PS 0 M 0p 0p 1p 4p 
Queue 1