universe = vanilla
Executable = /home/fsimpson/CMSSW_10_2_10/src/singleLepAnalyzer/makeTemplates/kinematics_PS_R17_OLD2/doCondorTemplates.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = condor_minMlb.out
Error = condor_minMlb.err
Log = condor_minMlb.log
Notification = Error
Arguments = /home/fsimpson/CMSSW_10_2_10/src/singleLepAnalyzer/makeTemplates/kinematics_PS_R17_OLD2 minMlb PS 0 R17 E 0p 0p 1p 4p
Queue 1