universe = vanilla
Executable = /home/fsimpson/CMSSW_10_2_10/src/singleLepAnalyzer/makeTemplates/kinematics_PS_R17_OLD/doCondorTemplates.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = condor_NJets.out
Error = condor_NJets.err
Log = condor_NJets.log
Notification = Error
Arguments = /home/fsimpson/CMSSW_10_2_10/src/singleLepAnalyzer/makeTemplates/kinematics_PS_R17_OLD NJets PS 0 R17 E 0p 0p 1p 4p
Queue 1