universe = vanilla
Executable = ET0pW0pB1pJ3plepPt.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = analyze.py,doHists.py,utils.py,weights.py,samples.py
request_memory = 3072
Output = condor_lepPt.out
Error = condor_lepPt.err
Log = condor_lepPt.log
Arguments = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_6_19/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates lepPt PS 0 E 0p 0p 1p 3p 
Queue 1