universe = vanilla
	Executable = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_2_10/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates/combineLimits/condor_step3_R17_kinematics_PS_2021_11_16_HT_lep100_MET100_DR1_HT510_jet1Pt200_jet2Pt100.sh
	Should_Transfer_Files = YES
	WhenToTransferOutput = ON_EXIT
	request_memory = 3072
	Output = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_2_10/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates/combineLimits/log/condor_step3_R17_kinematics_PS_2021_11_16_HT_lep100_MET100_DR1_HT510_jet1Pt200_jet2Pt100.out
	Error = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_2_10/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates/combineLimits/log/condor_step3_R17_kinematics_PS_2021_11_16_HT_lep100_MET100_DR1_HT510_jet1Pt200_jet2Pt100.err
	Log = /uscms_data/d3/fsimpson/scratch/FWLJMETstuff/CMSSW_10_2_10/src/ChargedHiggs/SingleLepAnalyzer/makeTemplates/combineLimits/log/condor_step3_R17_kinematics_PS_2021_11_16_HT_lep100_MET100_DR1_HT510_jet1Pt200_jet2Pt100.log
	Notification = Error
	Arguments = 
	Queue 1
